book_repo: incubator-hawq-docs/book

public_host: http://localhost:9292/

sections:
 - repository:
     name: incubator-hawq-docs/markdown
   directory: docs/userguide/2.3.0.0-incubating
   subnav_template: apache-hawq-nav

template_variables:
  use_global_header: true
  global_header_product_href: https://github.com/apache/incubator-hawq
  global_header_product_link_text: Downloads
  support_url: http://mail-archives.apache.org/mod_mbox/incubator-hawq-dev/
  product_url: http://hawq.incubator.apache.org/
  book_title: Apache HAWQ (incubating) Documentation
  support_link: <a href="https://issues.apache.org/jira/browse/HAWQ" target="_blank">Issues</a>
  support_call_to_action: <a href="https://issues.apache.org/jira/browse/HAWQ" target="_blank">Need Help?</a>
  product_link: <div class="header-item"><a href="http://hawq.incubator.apache.org/">Back to Apache HAWQ Page</a></div>
  book_title_short: Apache HAWQ (Incubating) Docs
